name: quickjs

on:
  [push]
jobs:
  # android:
  #   name: android
  #   runs-on: macos-10.15
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-java@v2
  #     with:
  #       distribution: temurin
  #       java-version: 11
  #       java-package: jdk
  #       architecture: x64
  #       cache: gradle
  #   - name: Download & install the Android SDK.
  #     uses: malinskiy/action-android/install-sdk@release/0.1.2
  #   - name: Set up platform tools like adb.
  #     run: sdkmanager platform-tools
  #   - name: Start ADB (and verify that pathing is working correctly).
  #     run: adb devices
  #   - name: Test(android)
  #     uses: malinskiy/action-android/emulator-run-cmd@release/0.1.2
  #     with:
  #       cmd: sh gradlew quack-android:connectedAndroidTest
  #       api: 25
  #       tag: default
  #       abi: x86
  #   - name: Assemble
  #     run: sh gradlew assemble
  #   - name: Save logcat output
  #     uses: actions/upload-artifact@v2
  #     if: failure()
  #     with:
  #       name: logcat
  #       path: artifacts/logcat.log
  #   - name: Archive result
  #     run: tar cvfz android.tar.gz quack-android/.cxx quack-android/build > /dev/null
  #   - name: Upload result
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: quickjs-android
  #       path: android.tar.gz
  publish:
    name: publish
    # needs: [android]
    runs-on: macos-10.15
    environment:
      name: actions
    steps:
    - name: Download windows library
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: quickjs.yml
        branch: master
        event: push
        search_artifacts: true
        name: quickjs-windows
        path: quack-jni/src/main/resources/META-INF/
    - name: Download linux library
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: quickjs.yml
        branch: master
        event: push
        search_artifacts: true
        name: quickjs-linux
        path: quack-jni/src/main/resources/META-INF/
    - name: Download macos library
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: quickjs.yml
        branch: master
        event: push
        search_artifacts: true
        name: quickjs-macos
        path: quack-jni/src/main/resources/META-INF/
    - name: Download android result
      uses: dawidd6/action-download-artifact@v2
      with:
        # workflow: quickjs.yml
        workflow: gh-pages.yml
        branch: actions
        event: push
        search_artifacts: true
        name: quickjs-android
        path: android.tar.gz
    - name: Expand result
      run: tar xvfz android.tar.gz
    - name: Generate
      run: |
        mkdir build
        mkdir build/mvn
        ls -lR > build/mvn/list.txt
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAGES }}
        external_repository: uk-taniyama/maven
        publish_branch: master
        publish_dir: ./build/mvn
        destination_dir: ./quack
        keep_files: true
