name: quickjs

on:
  [push]
jobs:
  windows:
    name: windows
    runs-on: windows-latest
    if: "contains(toJSON(github.event.commits.*.message), '[build windows]')"
    steps:
    - uses: actions/checkout@v2
      name: Checkout project
    # - uses: actions/setup-java@v1
    #   with:
    #     java-version: 11
    #     java-package: jdk
    #     architecture: x64
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: >-
          mingw64/mingw-w64-x86_64-cmake
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-ninja
    - name: Build
      shell: msys2 {0}
      run: sh native/build.sh
    # - name: Test
    #   run: |
    #      mvn --no-transfer-progress -q -B -DskipTests package
    #      mvn --no-transfer-progress test
    - name: Archive library
      uses: actions/upload-artifact@v2
      with:
        name: quickjs-windows
        path: quack-jni/src/main/resources/META-INF/quickjs.dll
  macos:
    name: macos
    runs-on: macos-10.15
    if: "contains(toJSON(github.event.commits.*.message), '[build macos]')"
    steps:
    - uses: actions/checkout@v2
      name: Checkout project
    - uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
        architecture: x64
    - name: Build
      run: sh native/build.sh
    # - name: Test
    #   run: |
    #      mvn --no-transfer-progress -q -B -DskipTests package
    #      mvn --no-transfer-progress test
    - name: Archive library
      uses: actions/upload-artifact@v2
      with:
        name: quickjs-macos
        path: quack-jni/src/main/resources/META-INF/libquickjs.dylib
  linux:
    name: linux
    runs-on: ubuntu-latest
    if: "contains(toJSON(github.event.commits.*.message), '[build linux]')"
    steps:
    - uses: actions/checkout@v2
      name: Checkout project
    - uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
        architecture: x64
    - name: Build
      run: bash native/build.sh
      # run: |
      #    mkdir -p src/main/resources/META-INF
      #    cd native
      #    mkdir build
      #    cd build
      #    cmake .. -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 -DCMAKE_BUILD_TYPE=Release
      #    make
      #    ldd libquickjs.so
      #    cp libquickjs.so ../../src/main/resources/META-INF
    # - name: Java Assemble
    #   run: |
    #      mvn --no-transfer-progress -q -B -DskipTests package
    #      mvn --no-transfer-progress test
    - name: Archive library
      uses: actions/upload-artifact@v2
      with:
        name: quickjs-linux
        path: quack-jni/src/main/resources/META-INF/libquickjs.so
  publish:
    name: publish
    if: ${{ ! failure() && contains(toJSON(github.event.commits.*.message), '[publish]')}}
    needs: [windows, macos, linux]
    runs-on: ubuntu-latest
    environment:
      name: actions

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
        architecture: x64
        cache: gradle
    - name: Download windows library
      uses: actions/download-artifact@v2
      with:
        name: quickjs-windows
    - name: Download linux library
      uses: actions/download-artifact@v2
      with:
        name: quickjs-linux
    - name: Download macos library
      uses: actions/download-artifact@v2
      with:
        name: quickjs-macos
    - name: Create local.properties
      run: touch local.properties
    - name: Show env
      run: env | sort
    - name: Build with Gradle
      env:
        maven_password: ${{secrets.MAVEN_PASSWORD}}
      run: sh gradlew publish
